fn main() {
    let lyrics = [
        "On the first day of Christmas",
        "My good friends brought to me",
        "A song and a Christmas tree",
        "On the second day of Christmas",
        "My good friends brought to me",
        "Two candy canes",
        "And a song for the Christmas tree",
        "On the third day of Christmas",
        "My good friends brought to me",
        "Three boughs of holly",
        "Two candy canes",
        "And a song for the Christmas tree",
        "On the fourth day of Christmas",
        "My good friends brought to me",
        "Four colored lights",
        "Three boughs of holly",
        "Two candy canes",
        "And a song for the Christmas tree",
        "On the fifth day of Christmas",
        "My good friends brought to me",
        "A shining star",
        "Four colored lights",
        "Three boughs of holly",
        "Two candy canes",
        "And a song for the Christmas tree",
        "On the sixth day of Christmas",
        "My good friends brought to me",
        "Little silver bells",
        "A shining star",
        "Four colored lights",
        "Three boughs of holly",
        "Two candy canes",
        "And a song for the Christmas tree",
        "On the seventh day of Christmas",
        "My good friends brought to me",
        "Candles a-glowing",
        "Little silver bells",
        "A shining star",
        "Four colored lights",
        "Three boughs of holly",
        "Two candy canes",
        "And a song for the Christmas tree",
        "On the eighth day of Christmas",
        "My good friends brought to me",
        "Gold and silver tinsel",
        "Candles a-glowing",
        "Little silver bells",
        "A shining star",
        "Four colored lights",
        "Three boughs of holly",
        "Two candy canes",
        "And a song for the Christmas tree",
        "On the ninth day of Christmas",
        "My good friends brought to me",
        "A guardian angel",
        "Gold and silver tinsel",
        "Candles a-glowing",
        "Little silver bells",
        "A shining star",
        "Four colored lights",
        "Three boughs of holly",
        "Two candy canes",
        "And a song for the Christmas tree",
        "On the tenth day of Christmas",
        "My good friends brought to me",
        "Some mistletoe",
        "A guardian angel",
        "Gold and silver tinsel",
        "Candles a-glowing",
        "Little silver bells",
        "A shining star",
        "Four colored lights",
        "Three boughs of holly",
        "Two candy canes",
        "And a song for the Christmas tree",
        "On the 11th day of Christmas",
        "My good friends brought to me",
        "Gifts for one and all",
        "Some mistletoe",
        "A guardian angel",
        "Gold and silver tinsel",
        "Candles a-glowing",
        "Little silver bells",
        "A shining star",
        "Four colored lights",
        "Three boughs of holly",
        "Two candy canes",
        "And a song for the Christmas tree",
        "On the 12th day of Christmas",
        "My good friends brought to me",
        "All their good wishes",
        "Gifts for one and all",
        "Some mistletoe",
        "A guardian angel",
        "Gold and silver tinsel",
        "Candles a-glowing",
        "Little silver bells",
        "A shining star",
        "Four colored lights",
        "Three boughs of holly",
        "Two candy canes",
        "And a song for the Christmas tree"
    ];

    for element in lyrics.iter() {
        println!("{}", element);
    }
}